security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
         main:
            pattern: ^/
            form_login:
                csrf_provider: form.csrf_provider
                check_path:  /user/login_check
                login_path:  /user/
                default_target_path:  /user/
            logout:
                path:   /user/logout
            remember_me:
                key:    "%secret%"
                name:   SIMPLE_BLOG_REMEMBER_ME
                lifetime: 36000
                path:     /
                domain:   ~
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }