acme_blog_homepage:
    pattern:  /
    defaults: { _controller: AcmeBlogBundle:Default:index }
acme_blog_page:
    pattern:  /page/{id}
    defaults: { _controller: AcmeBlogBundle:Default:page }
    requirements:
        id:  \d+
acme_blog_post:
    pattern:  /post/{id}/{url}
    defaults: { _controller: AcmeBlogBundle:Default:post, id : 1 }
    requirements:
        id:  \d+
acme_blog_post_add:
    pattern:  /post/add
    defaults: { _controller: AcmeBlogBundle:Default:add }

acme_blog_post_edit:
    pattern:  /post/edit/{id}
    defaults: { _controller: AcmeBlogBundle:Default:edit, id : 1 }
    requirements:
        id:  \d+
acme_blog_post_delete:
    pattern:  /post/delete/{id}
    defaults: { _controller: AcmeBlogBundle:Default:delete }
    requirements:
        id:  \d+
acme_blog_admin:
    path: /admin/
    defaults: { _controller: AcmeBlogBundle:Default:admin }

acme_blog_admin_page:
    pattern:  admin/page/{id}
    defaults: { _controller: AcmeBlogBundle:Default:adminpage }
    requirements:
        id:  \d+

acme_blog_post_tag:
    pattern:  /admin/tag
    defaults: { _controller: AcmeBlogBundle:Default:tag }

acme_blog_view_tag:
    pattern:  /post/tag/{id}
    defaults: { _controller: AcmeBlogBundle:Default:tags, id:1 }

acme_blog_view_tag_page:
    pattern:  /post/tag/{id}/page/{idp}
    defaults: { _controller: AcmeBlogBundle:Default:tagspage, id:1, idp:1 }

acme_blog_admin_comment:
    pattern:  /admin/comment/{id}
    defaults: { _controller: AcmeBlogBundle:Default:comment }

acme_blog_view_comment:
    pattern:  /admin/comment/view/{id}
    defaults: { _controller: AcmeBlogBundle:Default:commentview }

acme_blog_admin_comments:
    pattern:  /admin/comments
    defaults: { _controller: AcmeBlogBundle:Default:comments }

acme_blog_admin_comments_page:
    pattern:  /admin/comments/page/{id}
    defaults: { _controller: AcmeBlogBundle:Default:commentspage }

acme_blog_admin_option:
    pattern:  /admin/option
    defaults: { _controller: AcmeBlogBundle:Default:option }


