acme_blog_homepage:
    pattern:  /
    defaults: { _controller: AcmeBlogBundle:Default:index }
acme_blog_page:
    pattern:  /page/{id}
    defaults: { _controller: AcmeBlogBundle:Default:page }
    requirements:
        id:  \d+
acme_blog_post:
    pattern:  /post/{id}
    defaults: { _controller: AcmeBlogBundle:Default:post, id : 1 }
    requirements:
        id:  \d+
acme_blog_post_add:
    pattern:  /post/add
    defaults: { _controller: AcmeBlogBundle:Default:add }

acme_blog_post_edit:
    pattern:  /post/edit/{id}
    defaults: { _controller: AcmeBlogBundle:Default:edit, id : 1 }
    requirements:
        id:  \d+
acme_blog_post_form:
    path: /succes
    defaults: { _controller: AcmeBlogBundle:Default:success }
