acme_blog_homepage:
    pattern:  /
    defaults: { _controller: AcmeBlogBundle:Default:index }
acme_blog_page:
    pattern:  /page/{id}
    defaults: { _controller: AcmeBlogBundle:Default:page }
    requirements:
            id:  \d+
acme_blog_post:
    pattern:  /post/{id}
    defaults: { _controller: AcmeBlogBundle:Default:post }
    requirements:
            id:  \d+